apiVersion: v2
name: nexor
description: Nexor — real-time network observability platform
type: application
version: 0.7.0
appVersion: "0.7.0"
keywords:
  - networking
  - observability
  - security
  - pcap
  - ebpf
home: https://github.com/klyzar/nexor
sources:
  - https://github.com/klyzar/nexor
maintainers:
  - name: Klyzar
icon: https://raw.githubusercontent.com/klyzar/nexor/main/docs/logo.png
dependencies: []
