{{- if .Values.hub.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "nexor.name" . }}-hub
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nexor.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "nexor.name" . }}-hub
  minReplicas: {{ .Values.hub.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.hub.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hub.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
