apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netscope.name" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "netscope.labels" . | nindent 4 }}
type: Opaque
stringData:
  CLICKHOUSE_DSN: {{ .Values.hub.secret.clickhouseDSN | quote }}
  API_KEY: {{ .Values.hub.secret.apiKey | quote }}
